# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Enhanced debugging for exit code 1 troubleshooting.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: java -version
  displayName: 'Check Java Version'

- script: chmod +x gradlew
  displayName: 'Ensure Gradle Wrapper is Executable'

- script: ./gradlew dependencies --stacktrace
  displayName: 'Check Gradle Dependencies'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    options: '--stacktrace --info --debug -Xmx3072m'  # Added debug flags
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
